### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by sonaht** [DaKnOb/github-analytics#2]
Will it not be a better approach to have a config file for the env variables in order to be more versatile ?

A sample config file will suffice I hope.

What do you think ?

**Comment by daknob** [comment]
Do you think it is easier to manage environment variables or configuration files in a Docker project?

**Comment by sonaht** [comment]
Assuming we only use docker then setting variables inside the dockerfile is a solution. Assuming again that requirements do not change in such a way that we shall need to change the dockerfile in order to accommodate for a new env variable.

On the other hand a config file gives a certain air of freedom, docker or otherwise. We can always deploy this on a vm, or god forbid on a dedicated server 😜

**Comment by daknob** [comment]
Docker supports setting Environment Variables when using `docker run` or the respective Swarm command if you have a cluster. I am not sure the Swarm command is documented 100% because in my tests I figured out myself it was `--env-add` and `--add-env` depending on the implementation.

In addition to that, running this Python script will most likely be done with a WSGI Server, and all of them I know support passing ENV variables during the app execution.

**Comment by daknob** [comment]
If there is no objection, I can close this issue as `wontfix`.

**Comment by sonaht** [comment]
no problem as you like

**Comment by daknob** [comment]
Thank you!
